apiVersion: v1
kind: Service
metadata:
  name: {{ include "ns-resource-limiter.fullname" . }}
  labels:
{{ include "ns-resource-limiter.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: https
  selector:
    app: {{ include "ns-resource-limiter.name" . }}
